name: Launcher
main: com.eris.Launcher
version: ${project.version}
description: Redstone Launchpads
api-version: 1.16
commands:
  rslreload:
    description: Reloads the plugin's configuration.
permissions:
  rsl.launch:
    description: Can they be launched
    default: true
  rsl.reload:
    description: Can they reload the config
    default: op